version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: /go/src/github.com/influxdata/telegraf

    steps:
      - run:
          name:
          command: |
            go get -d github.com/influxdata/telegraf
