version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: /go/src/github.com/orangesys/telegraf-output-orangesys

    steps:
      - checkout
      - run: go get -d github.com/influxdata/telegraf
