version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: $HOME/telegraf-build

    environment:
      GOPATH: ~/telegraf-build
    steps:
      - checkout

      - run: go get -d github.com/influxdata/telegraf
