version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: ~/telegraf-build
    environment:
      GOPATH: ~/telegraf-build

    steps:
      - run:
        name: get influxdata telegraf
        command: |
          go get -d github.com/influxdata/telegraf
