version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: /go/src/github.com/orangesys/telegraf-output-orangesys

    steps:
      - checkout
      - run: go get -d github.com/influxdata/telegraf
      - run:
          command: |
            mv /go/src/github.com/orangesys/telegraf-output-orangesys \
            /go/src/github.com/influxdata/telegraf/plugins/outputs/orangesys
            sed -i '4i\t_ "github.com/influxdata/telegraf/plugins/outputs/orangesys"' \
            /go/src/github.com/influxdata/telegraf/plugins/outputs/all/all.go
      - run:
          commnad: |
            cd /go/src/github.com/influxdata/telegraf/
            go fmt ./...
            make
            go vet ./...
            telegraf -version
