version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: /telegraf-build

    environment:
      GOPATH: /telegraf-build
    steps:
      - checkout
      - run: mkdir -p $GOPATH
      - run: go get -d github.com/influxdata/telegraf
